import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from '@playwright/test';
import {createInterface} from 'node:readline';

// Actual browser against the actual Worker module, isolated KV for every test.
test('reviewer completes intake, editing, scoring and a deliberate G0 decision',async()=>{
 const proc=spawn('node',['engine/tests/worker-server.mjs'],{stdio:['ignore','pipe','pipe']});
 const line=createInterface({input:proc.stdout});
 const [port]=await once(line,'line');line.close();
 let browser;
 try{
  browser=await chromium.launch({headless:true,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${port}/login`);
  await page.locator('#email').fill('tester@example.com');await page.locator('#access_key').fill('test-key');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('button',{name:'+ New candidate'}).click();
  await page.getByLabel('Candidate name',{exact:true}).fill('Field Service');
  await page.getByLabel('What will this business deliver?').fill('Produce maintenance estimates for small contractors');
  await page.getByLabel('Buyer persona').fill('Contractor owner');
  await page.getByLabel('How will we reach this buyer?').fill('Trade association members');
  await page.getByLabel('If unassigned, explain the audience exception').fill('New audience under review');
  await page.getByLabel('If unassigned, explain the operator exception').fill('Operator recruitment pending');
  await page.locator('#submitmodal').click();
  await page.getByRole('heading',{name:'Field Service',exact:true}).waitFor();
  await page.getByRole('button',{name:'Reject',exact:true}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  assert.equal((await page.request.get(`http://127.0.0.1:${port}/api/candidates/field-service`)).status(),200);
  let record=await (await page.request.get(`http://127.0.0.1:${port}/api/candidates/field-service`)).json();
  assert.equal(record.decision,null,'Cancel must not decide');
  await page.getByRole('button',{name:'Edit declarations'}).click();
  await page.getByLabel('Opportunity lane').selectOption('substitution');
  await page.locator('#submitmodal').click();await page.locator('#modal').waitFor({state:'hidden'});
  for(const input of await page.locator('#scores input').all())await input.fill('4');
  for(const input of await page.locator('#scores textarea').all())await input.fill('Verified evidence for this dimension');
  await page.getByRole('button',{name:'Save scorecard',exact:true}).click();
  await page.locator('.score').filter({hasText:'40'}).waitFor();
  await page.getByLabel('Strongest case against this business').fill('Customer-specific estimating may be costly');
  await page.getByLabel('Falsifiable kill criterion').fill('Kill if no paid engagement in four weeks');
  await page.getByRole('button',{name:'Save case against',exact:true}).click();
  await page.getByText('Saved',{exact:true}).waitFor();
  await page.getByLabel('G1 · Reachability').fill('3% qualified replies');
  await page.getByLabel('G2 · Engagement').fill('3 paid engagements');
  await page.getByLabel('G3 · Retention').fill('1 repeat order');
  await page.getByRole('button',{name:'Save thresholds',exact:true}).click();
  await page.getByText('Saved',{exact:true}).waitFor();
  await page.getByLabel('Reviewer commentary').fill('Reviewed the evidence and economics');
  await page.getByRole('button',{name:'Save commentary',exact:true}).click();
  await page.locator('.memo').filter({hasText:'Reviewed the evidence and economics'}).waitFor();
  await page.screenshot({path:'.build/desktop-review.png',fullPage:true});
  await page.getByRole('button',{name:'Approve G0',exact:true}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  record=await (await page.request.get(`http://127.0.0.1:${port}/api/candidates/field-service`)).json();
  assert.equal(record.decision,null,'Cancel approval must not decide');
  await page.getByRole('button',{name:'Approve G0',exact:true}).click();
  await page.getByLabel('Decision rationale').fill('Thresholds set; proceed with bounded experiment');
  await page.getByRole('button',{name:'Confirm approval',exact:true}).click();
  await page.getByText('Decision locked',{exact:false}).waitFor();
  assert.equal(await page.locator('#scores input:enabled').count(),0);
  await page.getByRole('button',{name:'Configuration',exact:true}).click();
  await page.getByRole('button',{name:'+ Add cluster'}).click();
  await page.getByLabel('Identifier',{exact:true}).fill('field-services');await page.getByLabel('Name',{exact:true}).fill('Field Services');
  await page.locator('#submitmodal').click();await page.locator('#modal').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'+ Add operator'}).click();
  await page.getByLabel('Identifier',{exact:true}).fill('review-operator');await page.getByLabel('Name',{exact:true}).fill('Review Operator');
  await page.locator('#submitmodal').click();await page.locator('#modal').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'All candidates',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'.build/mobile-registry.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'No page-wide horizontal overflow');
  assert.deepEqual(errors,[]);
 }finally{if(browser)await browser.close();proc.kill();}
});
