const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function landing(l,interactive=false){return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(l.name)} · Test offer</title><style>body{background:#0d1420;color:#edf5fa;font:18px/1.6 system-ui;margin:0}main{max-width:850px;margin:auto;padding:50px 24px}h1{font-size:clamp(32px,6vw,60px);line-height:1.1}label{display:block;margin-top:16px}input,textarea,button{font:inherit;padding:12px;border-radius:8px;box-sizing:border-box}input,textarea{width:100%}button{background:#83d9cb;margin-top:24px;cursor:pointer}aside{background:#243445;padding:18px;border-radius:8px}small{color:#adc0cf}</style><main><aside>TEST PREVIEW · No payment is processed. Use fictional information only.</aside><p>${esc(l.name)}</p><h1>${esc(l.brand.headline)}</h1><h2>${esc(l.brand.offer)}</h2><p>${esc(l.brand.price_signal)}</p><form id="capture"><label for="actor">Test contact identifier</label><input id="actor" name="actor" required placeholder="test-buyer-1"><label for="scope">${l.candidate.delivery_mode==='service_first'?'What work do you need delivered?':'What workflow would you test?'}</label><textarea id="scope" required></textarea><button>${l.candidate.delivery_mode==='service_first'?'Request a test consultation':'Register test interest'}</button></form><p id="result" role="status"></p><p><small>${esc(l.brand.privacy)}</small></p>${interactive?'':'<aside>This exported scaffold is static. Wire the form to a reviewed CRM/capture endpoint before publication.</aside>'}</main>${interactive?`<script>
document.querySelector('#capture').onsubmit=async e=>{e.preventDefault();const out=document.querySelector('#result');try{const state=await(await fetch('/api/operations')).json();const actor=document.querySelector('#actor').value;const now=new Date().toISOString(),tag=crypto.randomUUID();const params=new URLSearchParams(location.search);const channel=params.get('utm_source')||'direct/unknown',angle=params.get('utm_content')||'unknown';const events=['visit','form_start','qualified_capture','booking'].slice(0,${l.candidate.delivery_mode==='service_first'?4:3}).map((event_type,i)=>({id:'preview-'+tag+'-'+i,event_type,actor,timestamp:now,channel,angle,details:event_type==='qualified_capture'?document.querySelector('#scope').value:''}));const r=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:state.revision,action:'signals.import',launch_id:${JSON.stringify(l.id)},events})});const b=await r.json();if(!r.ok)throw Error(b.detail);out.textContent='Test inquiry recorded. No email sent and no payment taken.';e.target.reset();}catch(error){out.textContent=error.message;}};
</script>`:''}</html>`;}
export function filesFor(p){const l=p.launch;return {
'README.md':`# ${l.name}\n\nGantry test handoff. This is a landing scaffold, not the completed venture product.\n\n## Run\n\nRequires Python 3.11+.\n\n\`\`\`bash\npython serve.py\n\`\`\`\n\nOpen http://localhost:8080. Run \`python smoke_test.py\`.\n\n## Deployment runbook\nReview positioning, privacy, contact handling and payment links. Implement and test the intended product and CRM adapter. Deploy static assets through an approved host; provision secrets outside git. Never publish this private evidence folder. Deploy only index.html and your approved assets, not the repository root.\n\n## Data\nEvidence is in private/*.json. CRM records are staged imports, not a verified provider export. Reconcile against Forum before handover. Shared cluster assets remain with the studio.\n`,
'index.html':landing(l),
'PRD.md':`# ${l.name}: launch brief\n\n${l.candidate.one_liner}\n\nBuyer: ${l.candidate.persona}\n\nChannel: ${l.candidate.channel}\n\nDelivery: ${l.candidate.delivery_mode}\n\nCase against: ${l.candidate.case_against}\n\nKill criterion: ${l.candidate.kill_criterion}\n\nAcceptance: meet the signed targets in private/launch.json. Product implementation remains the receiving team's work.\n`,
'ARCHITECTURE.md':'# Architecture\n\nStatic offer scaffold. Selection and operations evidence remain in Gantry. Add a reviewed contact endpoint, payment service, analytics and product runtime before a live test. No secrets are included.\n',
'ADR-0001.md':'# CSV integration boundary\n\nNeubloc, Vox and Forum APIs were not verified. Imported events are reviewer-supplied evidence. Replace staging with tested provider adapters before live automation. Preserve IDs for deduplication and channel attribution.\n',
'DEBT.md':'# Known debt\n\n- Static capture form: implement secure CRM capture before publication.\n- Payment and booking: configure verified external providers before taking money.\n- CRM staging: reconcile against Forum before operational handover.\n- Product: design and implement the actual offering before claiming product readiness.\n',
'private/launch.json':JSON.stringify(l,null,2),'private/signals.json':JSON.stringify(p.signals,null,2),'private/crm-staging.json':JSON.stringify(p.crm_staging,null,2),'private/audit.json':JSON.stringify(p.audit,null,2),'private/learnings.json':JSON.stringify(p.learnings,null,2),
'CHANNEL-PLAYBOOK.md':`# Channel playbook\n\n${JSON.stringify(l.playbook,null,2)}\n\nNo messages have been sent by this build. Require human approval, suppression checks and a dedicated sending domain before first send.\n`,
'serve.py':'from http.server import BaseHTTPRequestHandler, HTTPServer\nfrom pathlib import Path\nclass Page(BaseHTTPRequestHandler):\n    def do_GET(self):\n        if self.path != \"/\":\n            self.send_error(404); return\n        content = Path(\"index.html\").read_bytes()\n        self.send_response(200)\n        self.send_header(\"Content-Type\", \"text/html; charset=utf-8\")\n        self.end_headers()\n        self.wfile.write(content)\nHTTPServer((\"127.0.0.1\",8080), Page).serve_forever()\n',
'smoke_test.py':'from pathlib import Path\nimport json\nassert "TEST PREVIEW" in Path("index.html").read_text()\nlaunch = json.loads(Path("private/launch.json").read_text())\nassert launch["candidate"]["decision"]["approved"]\nassert set(launch["plan"]) == {"g1", "g2", "g3"}\nprint("Handoff scaffold and signed evidence are readable")\n',
'.gitignore':'.env\n__pycache__/\n*.pyc\n',
'.github/workflows/ci.yml':'name: Handoff checks\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.11"\n      - run: python smoke_test.py\n'
};}
